package: minify
version: '2.2'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/minify

page:
    title: 'translate:title'
    perm: minify[]
    pjax: true
    subpages:
        config: { title: 'translate:config', perm: minify[config] }
        sets: { title: 'translate:sets', perm: minify[sets] }
        clear_cache: { title: 'translate:minify_sets_function_clear_cache', itemclass: 'pull-right', linkclass: 'btn btn-delete', href: { page: minify/sets, cache: clear_cache } }
    
    requires:
        redaxo: '>=5.1.0'
        php:
            version: '>= 5.3'
