package: minify
version: '2.0.4'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/minify

page:
    title: 'translate:title'
    perm: minify[]
    pjax: true
    subpages:
        config: { title: 'translate:config', perm: minify[config] }
        sets: { title: 'translate:sets', perm: minify[sets] }